// stdsyms: 枚举目标 Go 二进制中标准库（strconv/strings/hash/unicode/os 等）
// 的包函数/方法 VA->name，用于把反汇编里未命名地址关联到 std 函数。
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/goretk/gore"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: stdsyms <binary> [filter-substr]")
		os.Exit(2)
	}
	f, err := gore.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, "open:", err)
		os.Exit(1)
	}
	defer f.Close()

	filter := ""
	if len(os.Args) >= 3 {
		filter = os.Args[2]
	}

	var collect func(p *gore.Package)
	collect = func(p *gore.Package) {
		if filter != "" && !strings.Contains(p.Name, filter) {
			return
		}
		for _, fn := range p.Functions {
			if filter == "" || strings.Contains(fn.Name, filter) {
				fmt.Printf("0x%x %s.%s\n", fn.Offset, p.Name, fn.Name)
			}
		}
		for _, m := range p.Methods {
			recv := strings.TrimSuffix(strings.TrimPrefix(m.Receiver, "(*"), ")")
			target := p.Name + "." + recv + "." + m.Name
			if filter == "" || strings.Contains(target, filter) {
				fmt.Printf("0x%x %s\n", m.Offset, target)
			}
		}
	}

	// 标准库
	if std, err := f.GetSTDLib(); err == nil {
		for _, p := range std {
			collect(p)
		}
	}
	// 第三方（wails 等 vendor）
	if v, err := f.GetVendors(); err == nil {
		for _, p := range v {
			collect(p)
		}
	}
	// 编译器生成（autogenerated，可能含 mapassign 等）
	if g, err := f.GetGeneratedPackages(); err == nil {
		for _, p := range g {
			collect(p)
		}
	}
	// 未知分类
	if u, err := f.GetUnknown(); err == nil {
		for _, p := range u {
			collect(p)
		}
	}
}